[versions]
minSdk = "21"
compileSdk = "31"
targetSdk = "31"

androidgradleplugin = "7.2.1"
gradle = '7.4.2'
kotlin = "1.7.0"
ktlint = "0.46.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-emoji-appcompat = { module = "androidx.emoji:emoji-appcompat", version = "1.1.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.4.0" }
espressocoreutils = { module = "com.vanniktech:espresso-core-utils", version = "0.4.0" }
falcon = { module = "com.jraska:falcon", version = "2.2.0" }
junit = { module = "junit:junit", version = "4.13.2" }
junitintegrationrules = { module = "com.vanniktech:junit4-android-integration-rules", version = "0.3.0" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.9.1" }
material = { module = "com.google.android.material:material", version = "1.6.1" }
plugin-android-cache-fix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version = "2.5.5" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-dependency-guard = { module = "com.dropbox.dependency-guard:dependency-guard", version = "0.3.1" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.7.10" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.4.1" }
plugin-metalava = { module = "me.tylerbwong.gradle:metalava-gradle", version = "0.2.3" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.20.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.8.1" }
screengrab = { module = "tools.fastlane:screengrab", version = "2.1.1" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.21.0" }
dependencygraphgenerator = { id = "com.vanniktech.dependency.graph.generator", version = "0.7.0" }
